//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EggFarmSystem.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LanguageData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EggFarmSystem.Resources.LanguageData", typeof(LanguageData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendance.
        /// </summary>
        public static string Attendance_Title {
            get {
                return ResourceManager.GetString("Attendance_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Consumable_ActiveField {
            get {
                return ResourceManager.GetString("Consumable_ActiveField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Consumable_NameField {
            get {
                return ResourceManager.GetString("Consumable_NameField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required.
        /// </summary>
        public static string Consumable_RequireName {
            get {
                return ResourceManager.GetString("Consumable_RequireName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Price is required.
        /// </summary>
        public static string Consumable_RequireUnitPrice {
            get {
                return ResourceManager.GetString("Consumable_RequireUnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumable.
        /// </summary>
        public static string Consumable_Title {
            get {
                return ResourceManager.GetString("Consumable_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Consumable_TypeField {
            get {
                return ResourceManager.GetString("Consumable_TypeField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string Consumable_UnitField {
            get {
                return ResourceManager.GetString("Consumable_UnitField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Price.
        /// </summary>
        public static string Consumable_UnitPriceField {
            get {
                return ResourceManager.GetString("Consumable_UnitPriceField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feed.
        /// </summary>
        public static string ConsumableType_Feed {
            get {
                return ResourceManager.GetString("ConsumableType_Feed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OVK.
        /// </summary>
        public static string ConsumableType_Ovk {
            get {
                return ResourceManager.GetString("ConsumableType_Ovk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumption.
        /// </summary>
        public static string Consumption_Title {
            get {
                return ResourceManager.GetString("Consumption_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard_Title {
            get {
                return ResourceManager.GetString("Dashboard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depreciation.
        /// </summary>
        public static string Depreciation_Title {
            get {
                return ResourceManager.GetString("Depreciation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Employee_ActiveField {
            get {
                return ResourceManager.GetString("Employee_ActiveField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Employee_NameField {
            get {
                return ResourceManager.GetString("Employee_NameField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required.
        /// </summary>
        public static string Employee_RequireName {
            get {
                return ResourceManager.GetString("Employee_RequireName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary is required.
        /// </summary>
        public static string Employee_RequireSalary {
            get {
                return ResourceManager.GetString("Employee_RequireSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary.
        /// </summary>
        public static string Employee_SalaryField {
            get {
                return ResourceManager.GetString("Employee_SalaryField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        public static string Employee_Title {
            get {
                return ResourceManager.GetString("Employee_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Egg Farm System.
        /// </summary>
        public static string General_AppTitle {
            get {
                return ResourceManager.GetString("General_AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General_Cancel.
        /// </summary>
        public static string General_Cancel {
            get {
                return ResourceManager.GetString("General_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string General_Delete {
            get {
                return ResourceManager.GetString("General_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this data?.
        /// </summary>
        public static string General_DeleteConfirmation {
            get {
                return ResourceManager.GetString("General_DeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string General_Edit {
            get {
                return ResourceManager.GetString("General_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string General_New {
            get {
                return ResourceManager.GetString("General_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string General_Refresh {
            get {
                return ResourceManager.GetString("General_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string General_Save {
            get {
                return ResourceManager.GetString("General_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Hen_ActiveField {
            get {
                return ResourceManager.GetString("Hen_ActiveField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        public static string Hen_CostField {
            get {
                return ResourceManager.GetString("Hen_CostField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string Hen_CountField {
            get {
                return ResourceManager.GetString("Hen_CountField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House.
        /// </summary>
        public static string Hen_HouseField {
            get {
                return ResourceManager.GetString("Hen_HouseField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count is invalid.
        /// </summary>
        public static string Hen_InvalidCount {
            get {
                return ResourceManager.GetString("Hen_InvalidCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Hen_NameField {
            get {
                return ResourceManager.GetString("Hen_NameField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost is required.
        /// </summary>
        public static string Hen_RequireCost {
            get {
                return ResourceManager.GetString("Hen_RequireCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required.
        /// </summary>
        public static string Hen_RequireName {
            get {
                return ResourceManager.GetString("Hen_RequireName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type is required.
        /// </summary>
        public static string Hen_RequireType {
            get {
                return ResourceManager.GetString("Hen_RequireType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hen.
        /// </summary>
        public static string Hen_Title {
            get {
                return ResourceManager.GetString("Hen_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Hen_TypeField {
            get {
                return ResourceManager.GetString("Hen_TypeField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string House_ActiveField {
            get {
                return ResourceManager.GetString("House_ActiveField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depreciation / day.
        /// </summary>
        public static string House_DepreciationField {
            get {
                return ResourceManager.GetString("House_DepreciationField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string House_NameField {
            get {
                return ResourceManager.GetString("House_NameField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Population.
        /// </summary>
        public static string House_PopulationField {
            get {
                return ResourceManager.GetString("House_PopulationField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Cost.
        /// </summary>
        public static string House_PurchaseCostField {
            get {
                return ResourceManager.GetString("House_PurchaseCostField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depreciation is required.
        /// </summary>
        public static string House_RequireDepreciation {
            get {
                return ResourceManager.GetString("House_RequireDepreciation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required.
        /// </summary>
        public static string House_RequireName {
            get {
                return ResourceManager.GetString("House_RequireName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase cost is required.
        /// </summary>
        public static string House_RequirePurchaseCost {
            get {
                return ResourceManager.GetString("House_RequirePurchaseCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year usage is required.
        /// </summary>
        public static string House_RequireYearUsage {
            get {
                return ResourceManager.GetString("House_RequireYearUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hen House.
        /// </summary>
        public static string House_Title {
            get {
                return ResourceManager.GetString("House_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year Usage.
        /// </summary>
        public static string House_YearUsageField {
            get {
                return ResourceManager.GetString("House_YearUsageField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Data.
        /// </summary>
        public static string Master_Title {
            get {
                return ResourceManager.GetString("Master_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production.
        /// </summary>
        public static string Production_Title {
            get {
                return ResourceManager.GetString("Production_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string Reports_Title {
            get {
                return ResourceManager.GetString("Reports_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumable.
        /// </summary>
        public static string Usage_ConsumableField {
            get {
                return ResourceManager.GetString("Usage_ConsumableField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string Usage_CountField {
            get {
                return ResourceManager.GetString("Usage_CountField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Usage_DateField {
            get {
                return ResourceManager.GetString("Usage_DateField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date is duplicate.
        /// </summary>
        public static string Usage_DuplicateDate {
            get {
                return ResourceManager.GetString("Usage_DuplicateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House.
        /// </summary>
        public static string Usage_HouseField {
            get {
                return ResourceManager.GetString("Usage_HouseField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage details information is required.
        /// </summary>
        public static string Usage_RequireDetails {
            get {
                return ResourceManager.GetString("Usage_RequireDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubTotal.
        /// </summary>
        public static string Usage_SubTotalField {
            get {
                return ResourceManager.GetString("Usage_SubTotalField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumable Usage.
        /// </summary>
        public static string Usage_Title {
            get {
                return ResourceManager.GetString("Usage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Usage_TotalField {
            get {
                return ResourceManager.GetString("Usage_TotalField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Price.
        /// </summary>
        public static string Usage_UnitPriceField {
            get {
                return ResourceManager.GetString("Usage_UnitPriceField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumable is required.
        /// </summary>
        public static string UsageDetail_RequireConsumable {
            get {
                return ResourceManager.GetString("UsageDetail_RequireConsumable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count is required.
        /// </summary>
        public static string UsageDetail_RequireCount {
            get {
                return ResourceManager.GetString("UsageDetail_RequireCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House is required.
        /// </summary>
        public static string UsageDetail_RequireHouse {
            get {
                return ResourceManager.GetString("UsageDetail_RequireHouse", resourceCulture);
            }
        }
    }
}
